'use strict';

/**
 * StackPick export-js-data.js
 *
 * Reads:  _data/products.json
 *         _data/collections.json
 * Writes: assets/js/data/products.js
 *         assets/js/data/collections.js
 *
 * These JS files are consumed by wall.js on the homepage.
 * They are auto-generated — do NOT edit them by hand.
 * Edit _data/products.json or _data/collections.json instead.
 *
 * Run standalone: node _generator/export-js-data.js
 * Called by:      _generator/build.js
 */

const fs   = require('fs');
const path = require('path');

const ROOT    = path.join(__dirname, '..');
const DATA    = path.join(ROOT, '_data');
const JS_DATA = path.join(ROOT, 'assets', 'js', 'data');

// ---------------------------------------------------------------------------
// Export products.js
// ---------------------------------------------------------------------------
function exportProducts() {
  const products = JSON.parse(fs.readFileSync(path.join(DATA, 'products.json'), 'utf8'));

  const header = [
    '// ============================================================',
    '//  AUTO-GENERATED by _generator/export-js-data.js',
    '//  DO NOT EDIT — edit _data/products.json instead',
    `//  Generated: ${new Date().toISOString()}`,
    '// ============================================================',
    '',
    '/* global window */',
    "window.SP_PRODUCTS = ",
  ].join('\n');

  const js = `${header}${JSON.stringify(products, null, 2)};\n`;
  fs.writeFileSync(path.join(JS_DATA, 'products.js'), js, 'utf8');
  console.log(`  ✓ assets/js/data/products.js (${products.length} products)`);
}

// ---------------------------------------------------------------------------
// Export collections.js
// ---------------------------------------------------------------------------
function exportCollections() {
  const collections = JSON.parse(fs.readFileSync(path.join(DATA, 'collections.json'), 'utf8'));

  const header = [
    '// ============================================================',
    '//  AUTO-GENERATED by _generator/export-js-data.js',
    '//  DO NOT EDIT — edit _data/collections.json instead',
    `//  Generated: ${new Date().toISOString()}`,
    '// ============================================================',
    '',
    '/* global window */',
    "window.SP_COLLECTIONS = ",
  ].join('\n');

  const js = `${header}${JSON.stringify(collections, null, 2)};\n`;
  fs.writeFileSync(path.join(JS_DATA, 'collections.js'), js, 'utf8');
  console.log(`  ✓ assets/js/data/collections.js (${collections.length} collections)`);
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------
function run() {
  exportProducts();
  exportCollections();
}

run();
