'use strict';

/**
 * StackPick export-js-data.js
 *
 * Reads:  _data/products.json
 *         _data/collections.json
 * Writes: assets/js/data/products.js
 *         assets/js/data/collections.js
 *
 * These JS files are consumed by wall.js on the homepage.
 * They are auto-generated — do NOT edit them by hand.
 * Edit _data/products.json or _data/collections.json instead.
 *
 * Run standalone: node _generator/export-js-data.js
 * Called by:      _generator/build.js (Step 6)
 */

const fs   = require('fs');
const path = require('path');

const ROOT    = path.join(__dirname, '..');
const DATA    = path.join(ROOT, '_data');
const JS_DATA = path.join(ROOT, 'assets', 'js', 'data');

// Ensure the output directory exists before any writes
try {
  fs.mkdirSync(JS_DATA, { recursive: true });
} catch (err) {
  throw new Error(`export-js-data: failed to create output directory "${JS_DATA}": ${err.message}`);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Load and parse a JSON data file with a descriptive error on failure. */
function loadJSON(filename) {
  const filePath = path.join(DATA, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(`export-js-data: missing data file "${filePath}"`);
  }
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (err) {
    throw new Error(`export-js-data: invalid JSON in "${filePath}": ${err.message}`);
  }
}

/** Write content to a file with a descriptive error on failure. */
function writeOutput(filePath, content) {
  try {
    fs.writeFileSync(filePath, content, 'utf8');
  } catch (err) {
    throw new Error(`export-js-data: failed to write "${filePath}": ${err.message}`);
  }
}

// ---------------------------------------------------------------------------
// Build the auto-generated file header.
// A single timestamp is computed once so both output files are in sync.
// ---------------------------------------------------------------------------
function buildHeader(globalVar, sourceFile, timestamp) {
  return [
    '// ============================================================',
    `//  AUTO-GENERATED by _generator/export-js-data.js`,
    `//  DO NOT EDIT — edit _data/${sourceFile} instead`,
    `//  Generated: ${timestamp}`,
    '// ============================================================',
    '',
    '/* global window */',
    `window.${globalVar} =`,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Export products.js
// ---------------------------------------------------------------------------
function exportProducts(timestamp) {
  const products = loadJSON('products.json');

  if (!Array.isArray(products) || products.length === 0) {
    throw new Error('export-js-data: products.json is empty or not an array — aborting export');
  }

  const js = `${buildHeader('SP_PRODUCTS', 'products.json', timestamp)}\n${JSON.stringify(products, null, 2)};\n`;
  writeOutput(path.join(JS_DATA, 'products.js'), js);
  console.log(`  ✓ assets/js/data/products.js (${products.length} products)`);
}

// ---------------------------------------------------------------------------
// Export collections.js
// ---------------------------------------------------------------------------
function exportCollections(timestamp) {
  const collections = loadJSON('collections.json');

  if (!Array.isArray(collections) || collections.length === 0) {
    throw new Error('export-js-data: collections.json is empty or not an array — aborting export');
  }

  const js = `${buildHeader('SP_COLLECTIONS', 'collections.json', timestamp)}\n${JSON.stringify(collections, null, 2)};\n`;
  writeOutput(path.join(JS_DATA, 'collections.js'), js);
  console.log(`  ✓ assets/js/data/collections.js (${collections.length} collections)`);
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------
function run() {
  // Single timestamp so both output files are byte-for-byte consistent
  const timestamp = new Date().toISOString();

  let passed = 0;
  let failed = 0;

  try {
    exportProducts(timestamp);
    passed++;
  } catch (err) {
    console.error(`  ✗ Failed to export products.js: ${err.message}`);
    failed++;
  }

  try {
    exportCollections(timestamp);
    passed++;
  } catch (err) {
    console.error(`  ✗ Failed to export collections.js: ${err.message}`);
    failed++;
  }

  console.log(`\n  Exported ${passed} file(s).${failed ? ` Failed: ${failed}.` : ''}`);

  // Propagate failure to the caller (build.js try/catch or process exit).
  // A partial export leaves stale/mismatched output files — the build must not continue.
  if (failed > 0) {
    throw new Error(`export-js-data: ${failed} export(s) failed — see errors above`);
  }
}

// FIX: guard with require.main to prevent auto-execution when imported by build.js
if (require.main === module) {
  run();
}

module.exports = { run };
