'use strict';

/**
 * StackPick export-js-data.js
 *
 * Reads:  _data/products.json
 *         _data/collections.json
 *         _data/comparisons.json
 *         _data/guides.json
 * Writes: assets/js/data/products.js
 *         assets/js/data/collections.js
 *         assets/js/data/search-index.js
 *
 * products.js and collections.js are consumed by wall.js on the homepage.
 * search-index.js is consumed by search/index.html.
 * All three are auto-generated — DO NOT edit them by hand.
 * Edit the _data/*.json source files instead.
 *
 * Run standalone: node _generator/export-js-data.js
 * Called by:      _generator/build.js (Step 6)
 */

const fs   = require('fs');
const path = require('path');

const ROOT    = path.join(__dirname, '..');
const DATA    = path.join(ROOT, '_data');
const JS_DATA = path.join(ROOT, 'assets', 'js', 'data');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Load and parse a JSON data file with a descriptive error on failure. */
function loadJSON(filename) {
  const filePath = path.join(DATA, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(`export-js-data: missing data file "${filePath}"`);
  }
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (err) {
    throw new Error(`export-js-data: invalid JSON in "${filePath}": ${err.message}`);
  }
}

/** Write content to a file with a descriptive error on failure. */
function writeOutput(filePath, content) {
  try {
    fs.writeFileSync(filePath, content, 'utf8');
  } catch (err) {
    throw new Error(`export-js-data: failed to write "${filePath}": ${err.message}`);
  }
}

// ---------------------------------------------------------------------------
// Build the auto-generated file header.
// A single timestamp is computed once so all output files are in sync.
// ---------------------------------------------------------------------------
function buildHeader(globalVar, sourceFiles, timestamp) {
  const sources = Array.isArray(sourceFiles) ? sourceFiles.join(', ') : sourceFiles;
  return [
    '// ============================================================',
    `//  AUTO-GENERATED by _generator/export-js-data.js`,
    `//  DO NOT EDIT — edit _data/${sources} instead`,
    `//  Generated: ${timestamp}`,
    '// ============================================================',
    '',
    '/* global window */',
    `window.${globalVar} =`,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Map a category name to its emoji — used in search index entries
// ---------------------------------------------------------------------------
const CATEGORY_EMOJI = {
  mice:      '🖱️',
  keyboards: '⌨️',
  headsets:  '🎧',
  monitors:  '🖥️',
  chairs:    '🪑',
  desks:     '🪵',
  speakers:  '🔊',
  pcs:       '💻',
  extras:    '✨',
};

// ---------------------------------------------------------------------------
// Export products.js
// ---------------------------------------------------------------------------
function exportProducts(timestamp) {
  const products = loadJSON('products.json');

  if (!Array.isArray(products) || products.length === 0) {
    throw new Error('export-js-data: products.json is empty or not an array — aborting export');
  }

  const js = `${buildHeader('SP_PRODUCTS', 'products.json', timestamp)}\n${JSON.stringify(products, null, 2)};\n`;
  writeOutput(path.join(JS_DATA, 'products.js'), js);
  console.log(`  ✓ assets/js/data/products.js (${products.length} products)`);

  return products;
}

// ---------------------------------------------------------------------------
// Export collections.js
// ---------------------------------------------------------------------------
function exportCollections(timestamp) {
  const collections = loadJSON('collections.json');

  if (!Array.isArray(collections) || collections.length === 0) {
    throw new Error('export-js-data: collections.json is empty or not an array — aborting export');
  }

  const js = `${buildHeader('SP_COLLECTIONS', 'collections.json', timestamp)}\n${JSON.stringify(collections, null, 2)};\n`;
  writeOutput(path.join(JS_DATA, 'collections.js'), js);
  console.log(`  ✓ assets/js/data/collections.js (${collections.length} collections)`);
}

// ---------------------------------------------------------------------------
// Export search-index.js
//
// Builds a flat array of search entries from products, comparisons, and guides.
// Each entry has: { type, icon, title, desc, price, url, tags }
// The search page (search/index.html) reads window.SP_SEARCH_INDEX.
// ---------------------------------------------------------------------------
function exportSearchIndex(products, timestamp) {
  const comparisons = loadJSON('comparisons.json');
  const guides      = loadJSON('guides.json');

  const entries = [];

  // ── Products ─────────────────────────────────────────────────────────────
  // Map category name to the search filter type used in the UI
  const CATEGORY_TYPE = {
    mice:      'mouse',
    keyboards: 'keyboard',
    headsets:  'headset',
    monitors:  'monitor',
    chairs:    'chair',
    desks:     'desk',
    speakers:  'speaker',
    pcs:       'pc',
    extras:    'extra',
  };

  products.forEach(p => {
    const type = CATEGORY_TYPE[p.category] || p.category;
    const icon = p.emoji || CATEGORY_EMOJI[p.category] || '🎮';
    const url  = `/${p.category}/`;

    // Build a rich tags string from all searchable fields
    const tags = [
      p.brand,
      p.name,
      p.shortName,
      p.category,
      type,
      ...(p.specs  || []),
      ...(p.tags   || []),
      ...(p.pros   || []),
    ].filter(Boolean).join(' ').toLowerCase();

    entries.push({
      type,
      icon,
      title: p.name,
      desc:  p.desc,
      price: p.price,
      url,
      tags,
    });
  });

  // ── Comparisons ───────────────────────────────────────────────────────────
  comparisons.forEach(c => {
    const url = `/comparisons/${c.slug}/`;

    const tags = [
      c.title,
      c.metaDescription || '',
      c.intro           || '',
      c.productA ? c.productA.name : '',
      c.productB ? c.productB.name : '',
      ...(c.specTable || []).map(row => `${row.a} ${row.b}`),
    ].filter(Boolean).join(' ').toLowerCase();

    entries.push({
      type:  'comparison',
      icon:  c.emoji || '⚖️',
      title: c.title,
      desc:  c.metaDescription || c.intro || '',
      price: null,
      url,
      tags,
    });
  });

  // ── Guides ───────────────────────────────────────────────────────────────
  guides.forEach(g => {
    const url = `/guides/${g.slug}/`;

    // Pull product names from guide sections for richer tag matching
    const sectionProductNames = [];
    if (Array.isArray(g.sections)) {
      g.sections.forEach(s => {
        if (Array.isArray(s.products)) {
          s.products.forEach(p => { if (p.name) sectionProductNames.push(p.name); });
        }
      });
    }

    const tags = [
      g.title,
      g.budget        || '',
      g.metaDescription || '',
      g.intro         || '',
      ...sectionProductNames,
    ].filter(Boolean).join(' ').toLowerCase();

    entries.push({
      type:  'guide',
      icon:  g.emoji || '📋',
      title: g.title,
      desc:  g.metaDescription || g.intro || '',
      price: g.budget || null,
      url,
      tags,
    });
  });

  const js = [
    buildHeader('SP_SEARCH_INDEX', ['products.json', 'comparisons.json', 'guides.json'], timestamp),
    '',
    JSON.stringify(entries, null, 2) + ';',
    '',
  ].join('\n');

  writeOutput(path.join(JS_DATA, 'search-index.js'), js);
  console.log(`  ✓ assets/js/data/search-index.js (${entries.length} entries: ${products.length} products, ${comparisons.length} comparisons, ${guides.length} guides)`);
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------
function run() {
  // Ensure the output directory exists before any writes
  try {
    fs.mkdirSync(JS_DATA, { recursive: true });
  } catch (err) {
    throw new Error(`export-js-data: failed to create output directory "${JS_DATA}": ${err.message}`);
  }

  // Single timestamp so all output files are byte-for-byte consistent
  const timestamp = new Date().toISOString();

  let passed = 0;
  let failed = 0;

  // products is returned so exportSearchIndex can reuse it without re-reading disk
  let products = null;

  try {
    products = exportProducts(timestamp);
    passed++;
  } catch (err) {
    console.error(`  ✗ Failed to export products.js: ${err.message}`);
    failed++;
  }

  try {
    exportCollections(timestamp);
    passed++;
  } catch (err) {
    console.error(`  ✗ Failed to export collections.js: ${err.message}`);
    failed++;
  }

  try {
    if (!products) {
      // products export failed — load directly so search index can still be built
      products = JSON.parse(fs.readFileSync(path.join(DATA, 'products.json'), 'utf8'));
    }
    exportSearchIndex(products, timestamp);
    passed++;
  } catch (err) {
    console.error(`  ✗ Failed to export search-index.js: ${err.message}`);
    failed++;
  }

  console.log(`\n  Exported ${passed} file(s).${failed ? ` Failed: ${failed}.` : ''}`);

  // Propagate failure to the caller (build.js try/catch or process exit).
  // A partial export leaves stale/mismatched output files — the build must not continue.
  if (failed > 0) {
    throw new Error(`export-js-data: ${failed} export(s) failed — see errors above`);
  }
}

if (require.main === module) {
  run();
}

module.exports = { run };
